baseURL = "https://wordsbydesign.co"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "wbd"
pagination.pagerSize = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@ginamc"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 1 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#080808'
  baseColor = "#fdfff5"
  baseOffsetColor = "#fffff0"
  headingColor = "#080808"
  textColor = "#080808"
  dotColor = "#080808"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Cardo"
  fontFamilyParagraph = "Montserrat"
  fontFamilyMonospace = "monospace"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.extensions.extras.subscript]
    enable = true
  [markup.goldmark.extensions.extras.superscript]
    enable = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Archive"
    identifier = "archives"
    weight = 3
    url = "/posts/"
  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 2
    url = "/tags/"
  [[menu.main]]
    name = "Subscribe"
    identifier = "subscribe"
    weight = 4
    url = "/subscribe/"